### ISSUE TITLE
glad to see update, but scaffolding has default texture, without glass

### ISSUE THREAD

**Issue by Ripoy** [Cyvack/Crystal-Clear-Arch#1]
glad to see update, but scaffolding has default texture, without glass. probably bc i use embeddium, i can try remove embeddium, if u need
casings works nicely
and my settings
[options.txt](https://github.com/user-attachments/files/15598174/options.txt)

**Comment by Cyvack** [comment]
The glass scaffolding use the default texture when they're placed down and a block is underneath them. Place them without a block underneath and they should have the glass casing texture on top

**Comment by Cyvack** [comment]
Reason for that is just because of it being annoying to walk through or climb, since you'd be having the glass texture hit your face constantly

**Comment by Ripoy** [comment]
ohhhh i didnt think about it

**Comment by Ripoy** [comment]
closed
