### ISSUE TITLE
Scaffolding blocks bug

### ISSUE THREAD

**Issue by Pipo-Samperi** [Cyvack/Crystal-Clear-Arch#2]
All of the scaffolding blocks don't render correctly the textures if there is any block underneath. they only render correcly if they are floating. The only other mod I was using was create so its not a compatibility issue bethween mods.

![Screenshot 2024-06-22 114424](https://github.com/Cyvack/Crystal-Clear-Arch/assets/173540814/9c3a9db4-eb06-42be-bbe0-d3b089293e66)

![Screenshot 2024-06-22 114450](https://github.com/Cyvack/Crystal-Clear-Arch/assets/173540814/07f997bc-e7a6-44aa-8020-e31a14717897)

**Comment by Cyvack** [comment]
Glass scaffolding not having its texture when placed on a block is intentional. https://github.com/Cyvack/Crystal-Clear-Arch/issues/1
